# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2fb3c6cb8e66c28a9e9ca55f8026105aaca44fad689de787cdf43ba4551b62b42df016d1d7d2ecd6019f3355e7117dc026b727947a63bcf708cf928bae3b64

test:
  secret_key_base: b1d87d21e9861b6f5c2b92c7c6593594e37669e273b1cea3bb2624bf7a2568c776d219c8fea6bef1c4f8d5bc7b51845b0f349588266d9b6c390fd89665d074d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
